# Generated by Django 4.0.5 on 2022-06-18 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('edad', models.IntegerField()),
                ('avatar', models.ImageField(max_length=50, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('id_kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_kid', to='registro.kid')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='pais',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Progreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partidas', models.IntegerField()),
                ('fecha', models.DateField(auto_now=True)),
                ('calificacion', models.IntegerField()),
                ('correctas', models.IntegerField()),
                ('fallidas', models.IntegerField()),
                ('id_nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_nivel', to='registro.nivel')),
            ],
        ),
        migrations.AddField(
            model_name='kid',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='id_user', to='registro.user'),
        ),
    ]
