# Generated by Django 4.0.5 on 2022-06-18 15:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_kid_nivel_alter_user_email_alter_user_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('stage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Progres',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('games', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('score', models.IntegerField()),
                ('correct', models.IntegerField()),
                ('fail', models.IntegerField()),
                ('id_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_level', to='registro.level')),
            ],
        ),
        migrations.RemoveField(
            model_name='progreso',
            name='id_nivel',
        ),
        migrations.RenameField(
            model_name='kid',
            old_name='edad',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='kid',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='pais',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='contraseña',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nombre',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='kid',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Nivel',
        ),
        migrations.DeleteModel(
            name='Progreso',
        ),
        migrations.AddField(
            model_name='level',
            name='id_kid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_kid', to='registro.kid'),
        ),
    ]
