# Generated by Django 4.0.5 on 2022-06-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_level_progres_remove_progreso_id_nivel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progres',
            name='score',
            field=models.DecimalField(decimal_places=1, max_digits=1),
        ),
    ]
