# Generated by Django 4.0.5 on 2022-06-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='avatar',
            field=models.CharField(max_length=50),
        ),
    ]
