# Generated by Django 4.0.5 on 2022-06-27 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_alter_kid_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registro.user'),
        ),
    ]
