# Generated by Django 4.0.5 on 2022-06-27 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_alter_kid_id_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kid',
            old_name='id_user',
            new_name='user',
        ),
    ]
