# Generated by Django 4.0.5 on 2022-06-27 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0008_rename_id_user_kid_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kid',
            name='user',
        ),
        migrations.AddField(
            model_name='kid',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id_user', to='registro.user'),
        ),
    ]
