# Generated by Django 4.0.5 on 2022-06-27 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0009_remove_kid_user_kid_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kid',
            name='id_user',
        ),
        migrations.AddField(
            model_name='kid',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_id', to='registro.user'),
        ),
    ]
