# Generated by Django 4.0.5 on 2022-06-27 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0010_remove_kid_id_user_kid_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kid',
            old_name='user_id',
            new_name='user',
        ),
    ]
