# Generated by Django 4.0.5 on 2022-06-28 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0011_rename_user_id_kid_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='id_kid',
        ),
        migrations.RemoveField(
            model_name='progres',
            name='id_level',
        ),
        migrations.AddField(
            model_name='level',
            name='kid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kid_id', to='registro.kid'),
        ),
        migrations.AddField(
            model_name='progres',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_id', to='registro.level'),
        ),
    ]
