# Generated by Django 4.0.5 on 2022-06-28 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0016_alter_kid_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
