# Generated by Django 4.0.5 on 2022-06-28 23:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0017_alter_kid_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
