# Generated by Django 4.0.5 on 2022-07-01 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0021_alter_progres_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='progres',
            name='kid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kid_p_id', to='registro.kid'),
        ),
    ]
