# Generated by Django 3.2.4 on 2022-07-07 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0022_progres_kid'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='level',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='type',
            field=models.IntegerField(null=True),
        ),
    ]
