# Generated by Django 4.0.5 on 2022-07-07 07:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0023_alter_kid_user_alter_level_kid_alter_progres_kid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('games', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('type', models.IntegerField(null=True)),
                ('score', models.DecimalField(decimal_places=1, max_digits=2)),
                ('correct', models.IntegerField()),
                ('fail', models.IntegerField()),
                ('kid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='registro.kid')),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='registro.level')),
            ],
        ),
        migrations.DeleteModel(
            name='Progres',
        ),
    ]
