# Generated by Django 3.2.4 on 2022-07-07 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0024_rename_level_level_lvl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='lvl',
        ),
    ]
