# Generated by Django 4.0.5 on 2022-07-16 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0024_progress_delete_progres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progress',
            old_name='type',
            new_name='area',
        ),
        migrations.RemoveField(
            model_name='level',
            name='stage',
        ),
        migrations.AddField(
            model_name='level',
            name='area',
            field=models.CharField(choices=[(1, 'letras'), (2, 'numeros')], max_length=1, null=True, verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='level',
            name='lvl',
            field=models.CharField(choices=[(1, 'Nivel 1'), (2, 'Nivel 2'), (3, 'Nivel 3')], max_length=1, null=True, verbose_name='Nivel'),
        ),
        migrations.AddField(
            model_name='level',
            name='status',
            field=models.CharField(choices=[(1, 'Bloqueado'), (2, 'Desbloqueado')], default=2, max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='level',
            name='kid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kid_id', to='registro.kid'),
        ),
    ]
