# Generated by Django 3.2.4 on 2022-07-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0025_remove_level_lvl'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='lvl',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
