# Generated by Django 4.0.5 on 2022-07-16 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0025_rename_type_progress_area_remove_level_stage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='lvl',
            new_name='stage',
        ),
    ]
