# Generated by Django 4.0.5 on 2022-07-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0026_rename_lvl_level_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='area',
            field=models.CharField(choices=[('1', 'letras'), ('2', 'numeros')], max_length=1, null=True, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='level',
            name='stage',
            field=models.CharField(choices=[('1', 'Nivel 1'), ('2', 'Nivel 2'), ('3', 'Nivel 3')], max_length=1, null=True, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='level',
            name='status',
            field=models.CharField(choices=[('1', 'Bloqueado'), ('2', 'Desbloqueado')], default=2, max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='area',
            field=models.CharField(choices=[('1', 'letras'), ('2', 'numeros')], max_length=1, null=True, verbose_name='Curso'),
        ),
    ]
