# Generated by Django 4.0.5 on 2022-07-12 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0028_alter_kid_user_alter_level_kid_alter_progres_kid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Progres',
            new_name='Progress',
        ),
    ]
